apiVersion: v1
kind: Template
metadata:
  creationTimestamp: null
  name: dockerbuild
objects:
- apiVersion: v1
  kind: ImageStream
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
      openshift.io/image.dockerRepositoryCheck: 2018-05-16T03:18:39Z
    creationTimestamp: null
    generation: 2
    labels:
      app: time
    name: rhel7
  spec:
    lookupPolicy:
      local: false
    tags:
    - annotations:
        openshift.io/imported-from: registry.access.redhat.com/rhel7
      from:
        kind: DockerImage
        name: docker-registry.default.svc:5000/dockerfile-shanna/rhel7:latest
      generation: 2
      importPolicy: {}
      name: latest
      referencePolicy:
        type: Source
  status:
    dockerImageRepository: ""
- apiVersion: v1
  kind: ImageStream
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    generation: 1
    labels:
      app: time
    name: time
  spec:
    lookupPolicy:
      local: false
    tags:
    - annotations: null
      from:
        kind: DockerImage
        name: docker-registry.default.svc:5000/dockerfile-shanna/time:latest
      generation: null
      importPolicy: {}
      name: latest
      referencePolicy:
        type: ""
  status:
    dockerImageRepository: ""
- apiVersion: v1
  kind: BuildConfig
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: time
    name: time
  spec:
    failedBuildsHistoryLimit: 5
    nodeSelector: null
    output:
      to:
        kind: ImageStreamTag
        name: time:latest
    postCommit: {}
    resources: {}
    runPolicy: Serial
    source:
      contextDir: rhel
      git:
        uri: https://github.com/VeerMuchandi/time
      type: Git
    strategy:
      dockerStrategy:
        from:
          kind: ImageStreamTag
          name: rhel7:latest
      type: Docker
    successfulBuildsHistoryLimit: 5
    triggers:
    - github:
        secret: NHdvyW1yFUnprSD5NUhL
      type: GitHub
    - generic:
        secret: 5Th6mwXbmYn1qrBWwUaL
      type: Generic
    - type: ConfigChange
    - imageChange: {}
      type: ImageChange
  status:
    lastVersion: 0
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    generation: 1
    labels:
      app: time
    name: time
  spec:
    replicas: 1
    revisionHistoryLimit: 10
    selector:
      app: time
      deploymentconfig: time
    strategy:
      activeDeadlineSeconds: 21600
      resources: {}
      rollingParams:
        intervalSeconds: 1
        maxSurge: 25%
        maxUnavailable: 25%
        timeoutSeconds: 600
        updatePeriodSeconds: 1
      type: Rolling
    template:
      metadata:
        annotations:
          openshift.io/generated-by: OpenShiftNewApp
        creationTimestamp: null
        labels:
          app: time
          deploymentconfig: time
      spec:
        containers:
        - image: docker-registry.default.svc:5000/dockerfile-shanna/time@sha256:cd33fd13ef9ff482600f76b7585a1fc289bdd9fd4f2a8d23bf93b398d259aa42
          imagePullPolicy: Always
          name: time
          ports:
          - containerPort: 8080
            protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
    test: false
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - time
        from:
          kind: ImageStreamTag
          name: time:latest
          namespace: dockerfile-shanna
      type: ImageChange
  status:
    availableReplicas: 0
    latestVersion: 0
    observedGeneration: 0
    replicas: 0
    unavailableReplicas: 0
    updatedReplicas: 0
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: time
    name: time
  spec:
    ports:
    - name: 8080-tcp
      port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      app: time
      deploymentconfig: time
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Route
  metadata:
    annotations:
      openshift.io/host.generated: "true"
    creationTimestamp: null
    labels:
      app: time
    name: time
  spec:
    host: time-dockerfile-shanna.apps.workshop.sc.osecloud.com
    port:
      targetPort: 8080-tcp
    to:
      kind: Service
      name: time
      weight: 100
    wildcardPolicy: None
  status:
    ingress:
    - conditions:
      - lastTransitionTime: 2018-05-16T03:21:15Z
        status: "True"
        type: Admitted
      host: time-dockerfile-shanna.apps.workshop.sc.osecloud.com
      routerName: router
      wildcardPolicy: None
